### ISSUE TITLE
Navigation menu

### ISSUE THREAD

**Issue by NiallEccles** [NiallEccles/kleur#17]
## Expected Behavior
Users should be able to navigate between the two current routes. "Homepage" which is just `/` and "New" which is `/new`.

## Actual Behavior
Currently there is no navigation menu so users cannot navigate to `/new` and back.

Updates should be made on a new branch called `feature/navigation-menu`.

**Comment by Yakup3** [comment]
Hi. Can I work on it?

**Comment by NiallEccles** [comment]
@Yakup3 Sure thing! We currently use Daisy UI in the project so it should be easy to replicate one of the examples [here](https://daisyui.com/components/navbar/)

**Comment by NiallEccles** [comment]
#20 merged! Good work!

**Comment by Yakup3** [comment]
Thanks 😃
